/**
 * mockData.js
 * Centralized mock data layer for dockMore multi-cloud storage aggregator.
 * All hardcoded accounts, files, folders, and transfers live here.
 */

import defaultAvatar from '../assets/icons/avatar.svg';

export const mockUser = {
  name: "Shreyansh Singh",
  email: "mailshreyanshhere@gmail.com",
  avatar: defaultAvatar,
  plan: "Pro Aggregator",
  joined: "January 2026",
};

export const mockAccounts = [
  {
    id: "acc-1",
    provider: "google-drive",
    providerName: "Google Drive",
    name: "Personal Drive",
    email: "mailshreyanshhere@gmail.com",
    usedStorageGB: 7.5,
    totalStorageGB: 15,
    status: "active",
    lastSynced: "2 mins ago",
    fileCount: 684,
  },
  {
    id: "acc-2",
    provider: "google-drive",
    providerName: "Google Drive",
    name: "Tech & Work",
    email: "shreyanshgottech@gmail.com",
    usedStorageGB: 10,
    totalStorageGB: 15,
    status: "active",
    lastSynced: "15 mins ago",
    fileCount: 942,
  },
  {
    id: "acc-3",
    provider: "onedrive",
    providerName: "OneDrive",
    name: "Microsoft Work",
    email: "reachbitsandgears@outlook.com",
    usedStorageGB: 2.5,
    totalStorageGB: 5,
    status: "active",
    lastSynced: "1 hour ago",
    fileCount: 231,
  },
  {
    id: "acc-4",
    provider: "mega",
    providerName: "MEGA",
    name: "Archives & Media",
    email: "mailshreyanshhere@gmail.com",
    usedStorageGB: 15,
    totalStorageGB: 20,
    status: "active",
    lastSynced: "Just now",
    fileCount: 130,
  },
  {
    id: "acc-5",
    provider: "dropbox",
    providerName: "Dropbox",
    name: "Client Vault",
    email: "shreyansh.studio@dropbox.com",
    usedStorageGB: 0,
    totalStorageGB: 5,
    status: "expired",
    lastSynced: "3 days ago",
    fileCount: 0,
  },
];

export const mockFolders = [
  {
    id: "fold-1",
    name: "FOLDER 1",
    provider: "google-drive",
    providerName: "Google Drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    accent: true, // First card uses the accent stacked black tab variant
  },
  {
    id: "fold-2",
    name: "FOLDER 2",
    provider: "onedrive",
    providerName: "OneDrive",
    accountEmail: "reachbitsandgears@outlook.com",
    accent: false,
  },
  {
    id: "fold-3",
    name: "FOLDER 3",
    provider: "mega",
    providerName: "MEGA",
    accountEmail: "maishreyanshhere@gmail.com",
    accent: false,
  },
  {
    id: "fold-4",
    name: "FOLDER 4",
    provider: "google-drive",
    providerName: "Google Drive",
    accountEmail: "shreyanshgottech@gmail.com",
    accent: false,
  },
];

export const mockFiles = [
  {
    id: "file-1",
    name: "Product_Design_System_v2.4.fig",
    type: "design",
    extension: "fig",
    size: "48.2 MB",
    sizeBytes: 50541363,
    provider: "google-drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    modified: "Today, 10:24 AM",
    path: "/Design System/2026/",
    folderId: "fold-1",
    starred: true,
  },
  {
    id: "file-2",
    name: "dockMore_Brand_Identity_Deck.pdf",
    type: "document",
    extension: "pdf",
    size: "14.8 MB",
    sizeBytes: 15518924,
    provider: "google-drive",
    accountEmail: "shreyanshgottech@gmail.com",
    modified: "Yesterday, 4:15 PM",
    path: "/Presentations/",
    folderId: "fold-1",
    starred: true,
  },
  {
    id: "file-3",
    name: "Enterprise_Cloud_Architecture_2026.docx",
    type: "document",
    extension: "docx",
    size: "3.2 MB",
    sizeBytes: 3355443,
    provider: "onedrive",
    accountEmail: "reachbitsandgears@outlook.com",
    modified: "Aug 29, 2026",
    path: "/Architecture/",
    folderId: "fold-2",
    starred: false,
  },
  {
    id: "file-4",
    name: "Production_Database_Dump_Aug26.tar.gz",
    type: "archive",
    extension: "tar.gz",
    size: "4.1 GB",
    sizeBytes: 4402341478,
    provider: "mega",
    accountEmail: "maishreyanshhere@gmail.com",
    modified: "Aug 26, 2026",
    path: "/Backups/DB/",
    folderId: "fold-3",
    starred: false,
  },
  {
    id: "file-5",
    name: "Client_Walkthrough_Recording.mp4",
    type: "video",
    extension: "mp4",
    size: "820 MB",
    sizeBytes: 859832320,
    provider: "google-drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    modified: "Aug 24, 2026",
    path: "/Recordings/",
    folderId: "fold-1",
    starred: false,
  },
  {
    id: "file-6",
    name: "Financial_Forecast_Q3_Q4_Model.xlsx",
    type: "spreadsheet",
    extension: "xlsx",
    size: "8.6 MB",
    sizeBytes: 9017753,
    provider: "onedrive",
    accountEmail: "reachbitsandgears@outlook.com",
    modified: "Aug 22, 2026",
    path: "/Finance/",
    folderId: "fold-2",
    starred: true,
  },
  {
    id: "file-7",
    name: "Hero_Motion_Render_ProRes422.mov",
    type: "video",
    extension: "mov",
    size: "2.4 GB",
    sizeBytes: 2576980377,
    provider: "mega",
    accountEmail: "maishreyanshhere@gmail.com",
    modified: "Aug 20, 2026",
    path: "/Media/Renders/",
    folderId: "fold-3",
    starred: false,
  },
  {
    id: "file-8",
    name: "dockMore_Icons_Master_Export.zip",
    type: "archive",
    extension: "zip",
    size: "95 MB",
    sizeBytes: 99614720,
    provider: "dropbox",
    accountEmail: "shreyansh.studio@dropbox.com",
    modified: "Aug 18, 2026",
    path: "/Assets/",
    folderId: "fold-4",
    starred: false,
  },
];

export const mockTransfers = [
  {
    id: "tr-1",
    filename: "Annual_Security_Audit_Report.pdf",
    size: "34.5 MB",
    sourceProvider: "google-drive",
    sourceAccount: "mailshreyanshhere@gmail.com",
    destinationProvider: "onedrive",
    destinationAccount: "reachbitsandgears@outlook.com",
    status: "in_progress",
    progress: 68,
    speed: "18.4 MB/s",
    eta: "8s remaining",
    timestamp: "Just now",
  },
  {
    id: "tr-2",
    filename: "Full_Project_Archive_2025.zip",
    size: "8.4 GB",
    sourceProvider: "mega",
    sourceAccount: "maishreyanshhere@gmail.com",
    destinationProvider: "google-drive",
    destinationAccount: "shreyanshgottech@gmail.com",
    status: "in_progress",
    progress: 32,
    speed: "24.2 MB/s",
    eta: "3m 40s remaining",
    timestamp: "4 mins ago",
  },
  {
    id: "tr-3",
    filename: "Brand_Identity_Assets_Vector.ai",
    size: "182 MB",
    sourceProvider: "dropbox",
    sourceAccount: "shreyansh.studio@dropbox.com",
    destinationProvider: "google-drive",
    destinationAccount: "mailshreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "15 mins ago",
  },
  {
    id: "tr-4",
    filename: "Product_Roadmap_2026_Q4.key",
    size: "45 MB",
    sourceProvider: "onedrive",
    sourceAccount: "reachbitsandgears@outlook.com",
    destinationProvider: "mega",
    destinationAccount: "maishreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "1 hour ago",
  },
  {
    id: "tr-5",
    filename: "HighRes_Photoshoot_RAW_Pack.tar",
    size: "14.2 GB",
    sourceProvider: "google-drive",
    sourceAccount: "shreyanshgottech@gmail.com",
    destinationProvider: "mega",
    destinationAccount: "maishreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "Yesterday, 6:30 PM",
  },
];

export const mockDashboardStats = {
  totalUsedGB: 35,
  totalCapacityGB: 45,
  connectedAccountsCount: 5,
  totalFilesCount: 1987,
  totalTransfersCount: 5,
  storageByProvider: [
    {
      name: "Google Drive",
      provider: "google-drive",
      used: 17.5,
      color: "#00AC47",
      accounts: [
        { name: "Personal Drive", email: "mailshreyanshhere@gmail.com", used: "7.5 GB" },
        { name: "Tech & Work", email: "shreyanshgottech@gmail.com", used: "10 GB" },
      ],
    },
    {
      name: "MEGA",
      provider: "mega",
      used: 15,
      color: "#D9272E",
      accounts: [
        { name: "Archives & Media", email: "mailshreyanshhere@gmail.com", used: "15 GB" },
      ],
    },
    {
      name: "OneDrive",
      provider: "onedrive",
      used: 2.5,
      color: "#0078D4",
      accounts: [
        { name: "Microsoft Work", email: "reachbitsandgears@outlook.com", used: "2.5 GB" },
      ],
    },
    {
      name: "Free Space",
      provider: "free",
      used: 10,
      color: "#D9D8D6",
      accounts: [],
    },
  ],
};

export const mockCodeProjects = [
  {
    id: "proj-1",
    name: "dockmore-cli",
    path: "~/projects/dockmore-cli",
    watchStatus: "watching",
    interval: 15,
    accountId: "acc-1",
    provider: "google-drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    snapshotCount: 48,
    lastSnapshot: "4 mins ago",
    lastCommitMessage: "feat: add shadow repository watcher & CLI flags",
    lastCommitTime: "2 hours ago",
    branch: "main",
  },
  {
    id: "proj-2",
    name: "dockmore-web",
    path: "~/projects/dockmore",
    watchStatus: "watching",
    interval: 15,
    accountId: "acc-3",
    provider: "onedrive",
    accountEmail: "reachbitsandgears@outlook.com",
    snapshotCount: 112,
    lastSnapshot: "11 mins ago",
    lastCommitMessage: "feat: implement unified transfers pipeline & real-time ETA",
    lastCommitTime: "Yesterday, 5:40 PM",
    branch: "main",
  },
  {
    id: "proj-3",
    name: "auth-bridge-service",
    path: "~/services/auth-bridge",
    watchStatus: "paused",
    interval: 20,
    accountId: "acc-4",
    provider: "mega",
    accountEmail: "mailshreyanshhere@gmail.com",
    snapshotCount: 26,
    lastSnapshot: "3 hours ago",
    lastCommitMessage: "fix: token refresh race condition and PKCE handshake",
    lastCommitTime: "3 days ago",
    branch: "auth/pkce",
  },
  {
    id: "proj-4",
    name: "cloud-storage-adapters",
    path: "~/libraries/storage-adapters",
    watchStatus: "watching",
    interval: 30,
    accountId: "acc-2",
    provider: "google-drive",
    accountEmail: "shreyanshgottech@gmail.com",
    snapshotCount: 64,
    lastSnapshot: "22 mins ago",
    lastCommitMessage: "refactor: streaming chunk uploader for MEGA and Dropbox",
    lastCommitTime: "4 days ago",
    branch: "feat/streaming",
  },
];

export const mockSnapshots = {
  "proj-1": [
    {
      id: "snap-101",
      projectId: "proj-1",
      hash: "7b4e9f1",
      summary: "4 files changed",
      details: "src/commands/watch.js, src/core/shadowGit.js (+48, -12)",
      timestamp: "4 mins ago",
      filesCount: 4,
      mirroredToCloud: true,
      size: "14.2 KB",
    },
    {
      id: "snap-102",
      projectId: "proj-1",
      hash: "a3c109d",
      summary: "2 files changed",
      details: "src/core/authPoll.js, package.json (+19, -4)",
      timestamp: "19 mins ago",
      filesCount: 2,
      mirroredToCloud: true,
      size: "6.8 KB",
    },
    {
      id: "snap-103",
      projectId: "proj-1",
      hash: "9f02e44",
      summary: "7 files changed",
      details: "src/commands/initialize.js, src/core/shadowGit.js (+102, -24)",
      timestamp: "34 mins ago",
      filesCount: 7,
      mirroredToCloud: true,
      size: "28.5 KB",
    },
    {
      id: "snap-104",
      projectId: "proj-1",
      hash: "e419b22",
      summary: "1 file changed",
      details: "README.md (+15, -2)",
      timestamp: "49 mins ago",
      filesCount: 1,
      mirroredToCloud: true,
      size: "3.1 KB",
    },
    {
      id: "snap-105",
      projectId: "proj-1",
      hash: "c208df7",
      summary: "5 files changed",
      details: "bin/dockmore.js, src/config.js, +3 more (+62, -18)",
      timestamp: "1 hour ago",
      filesCount: 5,
      mirroredToCloud: true,
      size: "18.4 KB",
    },
  ],
  "proj-2": [
    {
      id: "snap-201",
      projectId: "proj-2",
      hash: "5d83b1a",
      summary: "3 files changed",
      details: "src/pages/Transfers.jsx, src/context/TransfersContext.jsx (+36, -9)",
      timestamp: "11 mins ago",
      filesCount: 3,
      mirroredToCloud: true,
      size: "12.0 KB",
    },
    {
      id: "snap-202",
      projectId: "proj-2",
      hash: "318c4f2",
      summary: "6 files changed",
      details: "src/components/layout/Sidebar.jsx, src/App.jsx (+54, -16)",
      timestamp: "26 mins ago",
      filesCount: 6,
      mirroredToCloud: true,
      size: "22.3 KB",
    },
    {
      id: "snap-203",
      projectId: "proj-2",
      hash: "82a901c",
      summary: "1 file changed",
      details: "src/styles/theme.css (+8, -1)",
      timestamp: "41 mins ago",
      filesCount: 1,
      mirroredToCloud: true,
      size: "4.5 KB",
    },
  ],
  "proj-3": [
    {
      id: "snap-301",
      projectId: "proj-3",
      hash: "182ec04",
      summary: "2 files changed",
      details: "handlers/oauthCallback.go, middleware/jwt.go (+24, -6)",
      timestamp: "3 hours ago",
      filesCount: 2,
      mirroredToCloud: true,
      size: "9.2 KB",
    },
    {
      id: "snap-302",
      projectId: "proj-3",
      hash: "45f92d8",
      summary: "5 files changed",
      details: "config/vault.go, services/tokenStore.go (+84, -30)",
      timestamp: "3 hours 20 mins ago",
      filesCount: 5,
      mirroredToCloud: true,
      size: "19.8 KB",
    },
  ],
  "proj-4": [
    {
      id: "snap-401",
      projectId: "proj-4",
      hash: "d931bc7",
      summary: "4 files changed",
      details: "adapters/megaUploader.ts, adapters/dropboxChunker.ts (+72, -14)",
      timestamp: "22 mins ago",
      filesCount: 4,
      mirroredToCloud: true,
      size: "16.7 KB",
    },
    {
      id: "snap-402",
      projectId: "proj-4",
      hash: "601e89b",
      summary: "3 files changed",
      details: "interfaces/IStorageProvider.ts, tests/mega.test.ts (+45, -10)",
      timestamp: "52 mins ago",
      filesCount: 3,
      mirroredToCloud: true,
      size: "11.4 KB",
    },
  ],
};


