/**
 * mockData.js
 * Centralized mock data layer for dockMore multi-cloud storage aggregator.
 * All hardcoded accounts, files, folders, and transfers live here.
 */

export const mockUser = {
  name: "Shreyansh Singh",
  email: "mailshreyanshhere@gmail.com",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  plan: "Pro Aggregator",
  joined: "January 2026",
};

export const mockAccounts = [
  {
    id: "acc-1",
    provider: "google-drive",
    providerName: "Google Drive",
    name: "Personal Drive",
    email: "mailshreyanshhere@gmail.com",
    usedStorageGB: 7.5,
    totalStorageGB: 15,
    status: "active",
    lastSynced: "2 mins ago",
    fileCount: 684,
  },
  {
    id: "acc-2",
    provider: "google-drive",
    providerName: "Google Drive",
    name: "Tech & Work",
    email: "shreyanshgottech@gmail.com",
    usedStorageGB: 10,
    totalStorageGB: 15,
    status: "active",
    lastSynced: "15 mins ago",
    fileCount: 942,
  },
  {
    id: "acc-3",
    provider: "onedrive",
    providerName: "OneDrive",
    name: "Microsoft Work",
    email: "reachbitsandgears@outlook.com",
    usedStorageGB: 2.5,
    totalStorageGB: 5,
    status: "active",
    lastSynced: "1 hour ago",
    fileCount: 231,
  },
  {
    id: "acc-4",
    provider: "mega",
    providerName: "MEGA",
    name: "Archives & Media",
    email: "mailshreyanshhere@gmail.com",
    usedStorageGB: 15,
    totalStorageGB: 20,
    status: "active",
    lastSynced: "Just now",
    fileCount: 130,
  },
  {
    id: "acc-5",
    provider: "dropbox",
    providerName: "Dropbox",
    name: "Client Vault",
    email: "shreyansh.studio@dropbox.com",
    usedStorageGB: 0,
    totalStorageGB: 5,
    status: "expired",
    lastSynced: "3 days ago",
    fileCount: 0,
  },
];

export const mockFolders = [
  {
    id: "fold-1",
    name: "FOLDER 1",
    provider: "google-drive",
    providerName: "Google Drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    accent: true, // First card uses the accent stacked black tab variant
  },
  {
    id: "fold-2",
    name: "FOLDER 2",
    provider: "onedrive",
    providerName: "OneDrive",
    accountEmail: "reachbitsandgears@outlook.com",
    accent: false,
  },
  {
    id: "fold-3",
    name: "FOLDER 3",
    provider: "mega",
    providerName: "MEGA",
    accountEmail: "maishreyanshhere@gmail.com",
    accent: false,
  },
  {
    id: "fold-4",
    name: "FOLDER 4",
    provider: "google-drive",
    providerName: "Google Drive",
    accountEmail: "shreyanshgottech@gmail.com",
    accent: false,
  },
];

export const mockFiles = [
  {
    id: "file-1",
    name: "Product_Design_System_v2.4.fig",
    type: "design",
    extension: "fig",
    size: "48.2 MB",
    sizeBytes: 50541363,
    provider: "google-drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    modified: "Today, 10:24 AM",
    path: "/Design System/2026/",
    folderId: "fold-1",
    starred: true,
  },
  {
    id: "file-2",
    name: "dockMore_Brand_Identity_Deck.pdf",
    type: "document",
    extension: "pdf",
    size: "14.8 MB",
    sizeBytes: 15518924,
    provider: "google-drive",
    accountEmail: "shreyanshgottech@gmail.com",
    modified: "Yesterday, 4:15 PM",
    path: "/Presentations/",
    folderId: "fold-1",
    starred: true,
  },
  {
    id: "file-3",
    name: "Enterprise_Cloud_Architecture_2026.docx",
    type: "document",
    extension: "docx",
    size: "3.2 MB",
    sizeBytes: 3355443,
    provider: "onedrive",
    accountEmail: "reachbitsandgears@outlook.com",
    modified: "Aug 29, 2026",
    path: "/Architecture/",
    folderId: "fold-2",
    starred: false,
  },
  {
    id: "file-4",
    name: "Production_Database_Dump_Aug26.tar.gz",
    type: "archive",
    extension: "tar.gz",
    size: "4.1 GB",
    sizeBytes: 4402341478,
    provider: "mega",
    accountEmail: "maishreyanshhere@gmail.com",
    modified: "Aug 26, 2026",
    path: "/Backups/DB/",
    folderId: "fold-3",
    starred: false,
  },
  {
    id: "file-5",
    name: "Client_Walkthrough_Recording.mp4",
    type: "video",
    extension: "mp4",
    size: "820 MB",
    sizeBytes: 859832320,
    provider: "google-drive",
    accountEmail: "mailshreyanshhere@gmail.com",
    modified: "Aug 24, 2026",
    path: "/Recordings/",
    folderId: "fold-1",
    starred: false,
  },
  {
    id: "file-6",
    name: "Financial_Forecast_Q3_Q4_Model.xlsx",
    type: "spreadsheet",
    extension: "xlsx",
    size: "8.6 MB",
    sizeBytes: 9017753,
    provider: "onedrive",
    accountEmail: "reachbitsandgears@outlook.com",
    modified: "Aug 22, 2026",
    path: "/Finance/",
    folderId: "fold-2",
    starred: true,
  },
  {
    id: "file-7",
    name: "Hero_Motion_Render_ProRes422.mov",
    type: "video",
    extension: "mov",
    size: "2.4 GB",
    sizeBytes: 2576980377,
    provider: "mega",
    accountEmail: "maishreyanshhere@gmail.com",
    modified: "Aug 20, 2026",
    path: "/Media/Renders/",
    folderId: "fold-3",
    starred: false,
  },
  {
    id: "file-8",
    name: "dockMore_Icons_Master_Export.zip",
    type: "archive",
    extension: "zip",
    size: "95 MB",
    sizeBytes: 99614720,
    provider: "dropbox",
    accountEmail: "shreyansh.studio@dropbox.com",
    modified: "Aug 18, 2026",
    path: "/Assets/",
    folderId: "fold-4",
    starred: false,
  },
];

export const mockTransfers = [
  {
    id: "tr-1",
    filename: "Annual_Security_Audit_Report.pdf",
    size: "34.5 MB",
    sourceProvider: "google-drive",
    sourceAccount: "mailshreyanshhere@gmail.com",
    destinationProvider: "onedrive",
    destinationAccount: "reachbitsandgears@outlook.com",
    status: "in_progress",
    progress: 68,
    speed: "18.4 MB/s",
    eta: "8s remaining",
    timestamp: "Just now",
  },
  {
    id: "tr-2",
    filename: "Full_Project_Archive_2025.zip",
    size: "8.4 GB",
    sourceProvider: "mega",
    sourceAccount: "maishreyanshhere@gmail.com",
    destinationProvider: "google-drive",
    destinationAccount: "shreyanshgottech@gmail.com",
    status: "in_progress",
    progress: 32,
    speed: "24.2 MB/s",
    eta: "3m 40s remaining",
    timestamp: "4 mins ago",
  },
  {
    id: "tr-3",
    filename: "Brand_Identity_Assets_Vector.ai",
    size: "182 MB",
    sourceProvider: "dropbox",
    sourceAccount: "shreyansh.studio@dropbox.com",
    destinationProvider: "google-drive",
    destinationAccount: "mailshreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "15 mins ago",
  },
  {
    id: "tr-4",
    filename: "Product_Roadmap_2026_Q4.key",
    size: "45 MB",
    sourceProvider: "onedrive",
    sourceAccount: "reachbitsandgears@outlook.com",
    destinationProvider: "mega",
    destinationAccount: "maishreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "1 hour ago",
  },
  {
    id: "tr-5",
    filename: "HighRes_Photoshoot_RAW_Pack.tar",
    size: "14.2 GB",
    sourceProvider: "google-drive",
    sourceAccount: "shreyanshgottech@gmail.com",
    destinationProvider: "mega",
    destinationAccount: "maishreyanshhere@gmail.com",
    status: "completed",
    progress: 100,
    speed: null,
    eta: null,
    timestamp: "Yesterday, 6:30 PM",
  },
];

export const mockDashboardStats = {
  totalUsedGB: 35,
  totalCapacityGB: 45,
  connectedAccountsCount: 5,
  totalFilesCount: 1987,
  totalTransfersCount: 5,
  storageByProvider: [
    {
      name: "Google Drive",
      provider: "google-drive",
      used: 17.5,
      color: "#00AC47",
      accounts: [
        { name: "Personal Drive", email: "mailshreyanshhere@gmail.com", used: "7.5 GB" },
        { name: "Tech & Work", email: "shreyanshgottech@gmail.com", used: "10 GB" },
      ],
    },
    {
      name: "MEGA",
      provider: "mega",
      used: 15,
      color: "#D9272E",
      accounts: [
        { name: "Archives & Media", email: "mailshreyanshhere@gmail.com", used: "15 GB" },
      ],
    },
    {
      name: "OneDrive",
      provider: "onedrive",
      used: 2.5,
      color: "#0078D4",
      accounts: [
        { name: "Microsoft Work", email: "reachbitsandgears@outlook.com", used: "2.5 GB" },
      ],
    },
    {
      name: "Free Space",
      provider: "free",
      used: 10,
      color: "#D9D8D6",
      accounts: [],
    },
  ],
};


